/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  tutorialSidebar: [
    'intro',
    'features',    
    {
      type: 'category',
      label: 'Hamster Free',
      items: [
        {
          type: 'category',
          label: 'Mac',
          items: [
            'hamster-free/mac/install',      
            'hamster-free/mac/config',
            'hamster-free/mac/telemetry',              
          ],
        },
        {
          type: 'category',
          label: 'Windows',
          items: [
            'hamster-free/windows/install', 
            'hamster-free/windows/config',
            'hamster-free/windows/telemetry', 
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Hamster Pro',
      items: [
        {
          type: 'category',
          label: 'Mac',
          items: [
            'hamster-pro/mac/install', 
            'hamster-pro/mac/config',
            'hamster-pro/mac/telemetry',  
          ],
        },
        {
          type: 'category',
          label: 'Windows',
          items: [
            'hamster-pro/windows/install', 
            'hamster-pro/windows/config',
            'hamster-pro/windows/telemetry',          
          ],
        },
      ],
    },
  ],
  
};

export default sidebars;
